/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StudentsRouteImport } from './routes/students'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AssignmentsRouteImport } from './routes/assignments'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StudentsStudentIdRouteImport } from './routes/students.$studentId'
import { Route as EssaysEssayIdRouteImport } from './routes/essays.$essayId'
import { Route as AssignmentsAssignmentIdRouteImport } from './routes/assignments.$assignmentId'

const StudentsRoute = StudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AssignmentsRoute = AssignmentsRouteImport.update({
  id: '/assignments',
  path: '/assignments',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentsStudentIdRoute = StudentsStudentIdRouteImport.update({
  id: '/$studentId',
  path: '/$studentId',
  getParentRoute: () => StudentsRoute,
} as any)
const EssaysEssayIdRoute = EssaysEssayIdRouteImport.update({
  id: '/essays/$essayId',
  path: '/essays/$essayId',
  getParentRoute: () => rootRouteImport,
} as any)
const AssignmentsAssignmentIdRoute = AssignmentsAssignmentIdRouteImport.update({
  id: '/$assignmentId',
  path: '/$assignmentId',
  getParentRoute: () => AssignmentsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assignments': typeof AssignmentsRouteWithChildren
  '/login': typeof LoginRoute
  '/students': typeof StudentsRouteWithChildren
  '/assignments/$assignmentId': typeof AssignmentsAssignmentIdRoute
  '/essays/$essayId': typeof EssaysEssayIdRoute
  '/students/$studentId': typeof StudentsStudentIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assignments': typeof AssignmentsRouteWithChildren
  '/login': typeof LoginRoute
  '/students': typeof StudentsRouteWithChildren
  '/assignments/$assignmentId': typeof AssignmentsAssignmentIdRoute
  '/essays/$essayId': typeof EssaysEssayIdRoute
  '/students/$studentId': typeof StudentsStudentIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/assignments': typeof AssignmentsRouteWithChildren
  '/login': typeof LoginRoute
  '/students': typeof StudentsRouteWithChildren
  '/assignments/$assignmentId': typeof AssignmentsAssignmentIdRoute
  '/essays/$essayId': typeof EssaysEssayIdRoute
  '/students/$studentId': typeof StudentsStudentIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assignments'
    | '/login'
    | '/students'
    | '/assignments/$assignmentId'
    | '/essays/$essayId'
    | '/students/$studentId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/assignments'
    | '/login'
    | '/students'
    | '/assignments/$assignmentId'
    | '/essays/$essayId'
    | '/students/$studentId'
  id:
    | '__root__'
    | '/'
    | '/assignments'
    | '/login'
    | '/students'
    | '/assignments/$assignmentId'
    | '/essays/$essayId'
    | '/students/$studentId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssignmentsRoute: typeof AssignmentsRouteWithChildren
  LoginRoute: typeof LoginRoute
  StudentsRoute: typeof StudentsRouteWithChildren
  EssaysEssayIdRoute: typeof EssaysEssayIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/students': {
      id: '/students'
      path: '/students'
      fullPath: '/students'
      preLoaderRoute: typeof StudentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assignments': {
      id: '/assignments'
      path: '/assignments'
      fullPath: '/assignments'
      preLoaderRoute: typeof AssignmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/students/$studentId': {
      id: '/students/$studentId'
      path: '/$studentId'
      fullPath: '/students/$studentId'
      preLoaderRoute: typeof StudentsStudentIdRouteImport
      parentRoute: typeof StudentsRoute
    }
    '/essays/$essayId': {
      id: '/essays/$essayId'
      path: '/essays/$essayId'
      fullPath: '/essays/$essayId'
      preLoaderRoute: typeof EssaysEssayIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assignments/$assignmentId': {
      id: '/assignments/$assignmentId'
      path: '/$assignmentId'
      fullPath: '/assignments/$assignmentId'
      preLoaderRoute: typeof AssignmentsAssignmentIdRouteImport
      parentRoute: typeof AssignmentsRoute
    }
  }
}

interface AssignmentsRouteChildren {
  AssignmentsAssignmentIdRoute: typeof AssignmentsAssignmentIdRoute
}

const AssignmentsRouteChildren: AssignmentsRouteChildren = {
  AssignmentsAssignmentIdRoute: AssignmentsAssignmentIdRoute,
}

const AssignmentsRouteWithChildren = AssignmentsRoute._addFileChildren(
  AssignmentsRouteChildren,
)

interface StudentsRouteChildren {
  StudentsStudentIdRoute: typeof StudentsStudentIdRoute
}

const StudentsRouteChildren: StudentsRouteChildren = {
  StudentsStudentIdRoute: StudentsStudentIdRoute,
}

const StudentsRouteWithChildren = StudentsRoute._addFileChildren(
  StudentsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssignmentsRoute: AssignmentsRouteWithChildren,
  LoginRoute: LoginRoute,
  StudentsRoute: StudentsRouteWithChildren,
  EssaysEssayIdRoute: EssaysEssayIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
